server:
  port: 3000

db:
  database: "motonet_dev"
  host: "192.168.110.50"
  port: 27017
  options:
    replset:
      socketOptions:
        connectTimeoutMS : 2000

redis:
  host: "192.168.110.50"
  port: "6379"
  pass: null
  options: null

facebook:
  app_id: 1478417649072538
  app_secret: "0a807ddce0315a63f773342004042eeb"

web:
  domain: "http://localhost:8000"