server:
  port: 16682

db:
  database: "ride-plan"
  host: "127.0.0.1"
  port: 27017
  options:
    replset:
      socketOptions:
        connectTimeoutMS : 8000

redis:
  host: "redis://redistogo:aa637d5a3c5fc2ac729861931763f91d@jack.redistogo.com"
  port: 10741
  pass: null
  options: null

facebook:
  app_id: 1478417649072538
  app_secret: "0a807ddce0315a63f773342004042eeb"

web:
  domain: "http://http://ec2-54-77-33-132.eu-west-1.compute.amazonaws.com:16682"