app:
  user_id_salt: 5xKfBHK5UE6M0JDbCdCUM6ABZ07aXysaDhVF10CHVtvArmk79it1gGMnprM7RR7O

server:
  port: 3000

db:
  database: "motonet_test"
  host: "192.168.110.50"
  port: 27017
  options:
    replset:
      socketOptions:
        connectTimeoutMS : 2000

redis:
  host: "192.168.110.50"
  port: "6379"
  pass: null
  options: null

facebook:
  app_id: 1478753505705619
  app_secret: "51df55fc5c7a9a7e555d8ec26e131f72"